version: '3'
services:
  nifi:
    image: apache/nifi:latest
    ports:
      - "172.17.0.1:8080:8080"
    volumes:
      - nifi_data:/opt/nifi/nifi-current/flowfile_repository
      - nifi_data:/opt/nifi/nifi-current/content_repository
      - nifi_data:/opt/nifi/nifi-current/provenance_repository
      - nifi_data:/opt/nifi/nifi-current/conf/state