version: '3.3'
services:
    nifi:
        image: 'apache/nifi:latest'
        restart: always
        ports:
            - '172.17.0.1:8448:8443'
        environment:
            - SINGLE_USER_CREDENTIALS_USERNAME=admin
            - SINGLE_USER_CREDENTIALS_PASSWORD=${ADMIN_PASSWORD}
        volumes:
            - ./database_repository:/opt/nifi/nifi-current/database_repository
            - ./flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
            - ./content_repository:/opt/nifi/nifi-current/content_repository
            - ./provenance_repository:/opt/nifi/nifi-current/provenance_repository
            - ./state:/opt/nifi/nifi-current/state
            - ./logs:/opt/nifi/nifi-current/logs