version: '3.3'
services:
    nifi:
        image: 'apache/nifi:${SOFTWARE_VERSION_TAG}'
        restart: always
        hostname: ${DOMAIN}
        ports:
            - '172.17.0.1:8448:8448'
        environment:
            - SINGLE_USER_CREDENTIALS_USERNAME=admin
            - SINGLE_USER_CREDENTIALS_PASSWORD=${ADMIN_PASSWORD}
            - NIFI_WEB_HTTPS_PORT=8448
            - NIFI_WEB_PROXY_HOST=172.17.0.1:8448
        volumes:
            - ./database_repository:/opt/nifi/nifi-current/database_repository
            - ./flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
            - ./content_repository:/opt/nifi/nifi-current/content_repository
            - ./provenance_repository:/opt/nifi/nifi-current/provenance_repository
            - ./state:/opt/nifi/nifi-current/state
            - ./logs:/opt/nifi/nifi-current/logs
            - nifi-conf:/opt/nifi/nifi-current/conf
volumes:
  nifi-conf:
    driver: local
    driver_opts:
     type: none
     device: ${PWD}/conf
     o: bind
